In [2]:
from tensorflow.keras.datasets import fashion_mnist

(x_train,y_train), (x_test, y_test)=fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 7us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 11s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 4s 1us/step


In [4]:
x_train=x_train/255
x_test=x_test/255

In [6]:
print(x_train.min(), x_train.max())
print(x_test.min(), x_test.max())
print(x_train.dtype)

0.0 1.0
0.0 1.0
float64


In [8]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [20]:
import numpy as np 
print(np.unique(y_train))

[0 1 2 3 4 5 6 7 8 9]


In [10]:
x_train.reshape(-1, 28,28, 1)
x_test.reshape(-1, 28, 28, 1)

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [14]:
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.models import Sequential
import tensorflow as ft

In [16]:
model=Sequential()
model.add(layers.Conv2D(32, (3,3),
                        activation='relu', input_shape=(28,28, 1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3),
                        activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(128, (3,3),
                        activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

In [21]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

In [22]:
model.compile(optimizer='adam',
              loss=ft.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])


In [23]:
model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=10
)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 30s 14ms/step - accuracy: 0.7922 - loss: 0.5696 - val_accuracy: 0.8254 - val_loss: 0.4671
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - accuracy: 0.8577 - loss: 0.3854 - val_accuracy: 0.8621 - val_loss: 0.3775
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - accuracy: 0.8776 - loss: 0.3283 - val_accuracy: 0.8782 - val_loss: 0.3356
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - accuracy: 0.8927 - loss: 0.2901 - val_accuracy: 0.8786 - val_loss: 0.3270
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 28s 15ms/step - accuracy: 0.9006 - loss: 0.2640 - val_accuracy: 0.8884 - val_loss: 0.3100
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.9107 - loss: 0.2392 - val_accuracy: 0.8905 - val_loss: 0.3039
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 26s 14ms/step - accuracy: 0.9191 - loss: 0.2184 - val_accuracy: 0.8891 - val_loss: 0.3091
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 14ms/step - accuracy: 0.9246 -

In [25]:
prediction=model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step


In [26]:
prediction[0]

array([-6.3926682 , -9.041768  , -8.995407  , -6.4553943 , -8.321183  ,
       -0.29343128, -4.869559  ,  2.0907626 , -6.9827733 , 10.892512  ],
      dtype=float32)

In [27]:
model.save("fashion_mnist_cnn.h5")